/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>

//RCC
#define RCC_BASE   0x40021000
#define RCC_APB2ENR *((volatile uint32_t *)(RCC_BASE + 0x18))

//GPIO
#define GPIOA_BASE  0x40010800
#define GPIOA_CRH    *((volatile uint32_t *)(GPIOA_BASE + 0x4))
#define GPIOA_ODR    *((volatile uint32_t *)(GPIOA_BASE + 0x0c))
#define GPIOA_CRL    *((volatile uint32_t *)(GPIOA_BASE + 0x00))

//AFIO
#define AFIO_BASE       0x40010000
#define AFIO_EXTICR1    *((volatile uint32_t *)(AFIO_BASE + 0x08))

//EXTI
#define EXTI_BASE   0x40010400
#define EXTI_IMR    *((volatile uint32_t *)(EXTI_BASE + 0x00))
#define EXTI_RTSR    *((volatile uint32_t *)(EXTI_BASE + 0x08))
#define EXTI_PR    *((volatile uint32_t *)(EXTI_BASE + 0x14))

#define NVIC_EXTIE0    *((volatile uint32_t *)(0xE000E100))

void clock_init()
{
	//enable GPIOA clock
	RCC_APB2ENR  |= (1<<2);
	//enable AFIO clock
	RCC_APB2ENR |= (1<<0);
}

void GPIO_init()
{
	//pin 13 port A is output
	GPIOA_CRH     &= 0xff0fffff; // reset imp bits 20-23 and maintaining the rest (calibration)
	GPIOA_CRH     |= 0x00200000;
	//pin A0 input floating
	GPIOA_CRL |= (1<<2);
}

int main(void)
{
	clock_init();
	GPIO_init();

	//EXTI0 configuration to PORTA0
	AFIO_EXTICR1=0;

	//enable rising trigger
	EXTI_RTSR |= (1<<0);

	//enable EXTI line 0 (mask 1)
	EXTI_IMR |= (1<<0);

	//enable NVIC IRQ6 <<>> EXTI0
	NVIC_EXTIE0 |= (1<<6);


	while(1) ;

	return 0;
}
void EXTI0_IRQHandler (void)
{
	//IRQ has happened EXTTI0 >> PORTA pin 0 >> rising edge
	//toggle led pin 13
	GPIOA_ODR ^=(1<<13);

	//clear pending request for line 0
	EXTI_PR |= (1<<0);
}
